import java.util.*;
import java.io.*;

public class Test {
    static BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    static PrintWriter pr = new PrintWriter(new BufferedWriter(new OutputStreamWriter(System.out)));
    static StringTokenizer st;

    public static void main(String[] args) throws IOException {
        int n = 0;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
          n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
   n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;

        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;n = 1;n = 1;n = 1;n = 1;
        n = 1;n = 1;
        n = 1;n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;
        n = 1;












    }


    static class edge implements Comparable<edge> {
        int v, w;

        edge(int v0, int w0) {
            v = v0;
            w = w0;
        }

        public int compareTo(edge x) {
            return Integer.compare(w, x.w);
        }
    }

    static class pair {
        int r, c;

        pair(int r0, int c0) {
            r = r0;
            c = c0;
        }
    }

    static String next() throws IOException {
        while (st == null || !st.hasMoreTokens())
            st = new StringTokenizer(br.readLine().trim());
        return st.nextToken();
    }

    static long readLong() throws IOException {
        return Long.parseLong(next());
    }

    static int readInt() throws IOException {
        return Integer.parseInt(next());
    }

    static double readDouble() throws IOException {
        return Double.parseDouble(next());
    }

    static char readCharacter() throws IOException {
        return next().charAt(0);
    }

    static String readLine() throws IOException {
        return br.readLine().trim();
    }
}
